### ISSUE TITLE
Option for highlighting anywhere in the text

### ISSUE THREAD

**Issue by benjamindulau** [moroshko/autosuggest-highlight#5] opened 2017-07-19 15:48 UTC
I really like the simplicity of this utility.
The only thing missing for me is an option to highlight anywhere in any word.

I have a use case where I need to highlight different type of content in the same results, i.e:

Query: M
Result:
170627-LMP-8Y42
Marc Lecomte

For now I get:
170627-LMP-8Y42
**M**arc Lecomte

But I'd like:
170627-L**M**P-8Y42  (Here I want to highlight anywhere in the expression)
**M**arc Lecomte (Here the default behavior is OK)

Would you consider adding such option?

Cheers

**Comment by moroshko** [comment] 2017-07-20 05:18
I have the feeling that this would significantly complicate the implementation.
But, I'm happy to be proven wrong, so PR is welcome!

**Comment by marcusjwhelan** [comment] 2017-09-07 17:51
Sorry in Typescript but I did get the results I wanted. This is for a custom use So I wasn't making it to work for every case just my own. 

```typescript
const match = (text: any, query: any)  => {

    return (
        query
            .trim()
            .split(whitespacesRegex)
            // If query is blank, we'll get empty string here, so let's filter it out.
            .filter((word: any) => {
                return word.length > 0;
            })
            .reduce((result: any, word: any) => {
                const wordLen = word.length;
                const regex = new RegExp(escapeRegexCharacters(word), 'i');
                const index = text.match(regex).index;
                if (index > -1) {
                    result.push([index, index + wordLen]);

                    // Replace what we just found with spaces so we don't find it again.
                    text =
                        text.slice(0, index) +
                        new Array(wordLen + 1).join(' ') +
                        text.slice(index + wordLen);
                }

                return result;
            }, [])
            .sort((match1: any, match2: any) => {
                return match1[0] - match2[0];
            })
    );
};
```

**Comment by marcusjwhelan** [comment] 2017-09-07 17:59
@moroshko is this valid? if so could I make a pull request?

**Comment by toolchild** [comment] 2017-09-08 13:31
@marcusjwhelan 
I did test it after removing the typescript specific type descriptions and using the undeclared variables from the original `match.js`. 
When i have a text containing `display` and a query `isplay` it doesn't highlight. So I didn't see how it behaves differently from the original code, in my specific use-case.  : - (
But I didn't put much time into it.

**Comment by marcusjwhelan** [comment] 2017-09-11 19:52
Well I have a working two separate word autoSuggest going with highlighting on both separate words on any letter in them not starting from the beginning.

**Comment by iki** [comment] 2017-11-14 09:58
@marcusjwhelan Great! Can you pls make PR here? I can test it, we need it too.

**Comment by marcusjwhelan** [comment] 2017-11-14 14:04
@iki I guess I will just post all the code for it.

```typescript
import React, {Component} from 'react';
import {withStyles} from 'material-ui/styles';
import {MenuItem} from 'material-ui/Menu';
import Autosuggest from 'react-autosuggest';
import Paper from 'material-ui/Paper';
import {getPath} from 'tedb';
import {Iuser} from '../../../api/models';
import {FormControl, Input} from 'material-ui';
import {match} from '../../../helpers/autoSuggestHightlight';
const parse = require('autosuggest-highlight/parse');

const relative: any = 'relative';
const absolute: any = 'absolute';

const styles = (theme: any) => ({
    container: {
        flexGrow: 1,
        backgroundColor: 'white',
        position: relative,
    },
    suggestionsContainerOpen: {
        zIndex: 5,
        position: absolute,
        left: 0,
        right: 0,
    },
    suggestion: {
        display: 'block',
        position: relative,
    },
    suggestionsList: {
        position: relative,
        margin: 0,
        padding: 0,
        listStyleType: 'none',
    },
    textField: {
        width: '100%',
        margin: 0,
    },
});

const renderSuggestionsContainer = (options: any) => {
    const {containerProps, children} = options;
    return (
        <Paper {...containerProps} square>
            {children}
        </Paper>
    );
};

const renderInput = (inputProps: any) => {
    const {classes, home, value, ref, parentClasses, ...other} = inputProps;

    return (
        <FormControl
            className={classes.textField}
            margin="dense"
            fullWidth={true}
        >
            <Input className={parentClasses.inputField}
                   value={value}
                   autoFocus={home}
                   inputRef={ref}
                   {...other}
            />
        </FormControl>
    );
};

interface IUserAutoCompleteStyles {
    classes: any;
}

interface IUserAutoCompleteInjectedProps {
    parentClasses: any;
    objects: any[];
    path1: string;
    path2: string;
    disabled: boolean;
    value: any;
    name: string;
    save: (obj: any, name: string, path: string) => any;
    getSuggestionValue: (suggestion: any) => any;
    getSuggestions: (value: any, suggestions: any[]) => any[];
    onSuggestionSelected: (event: any, obj: any) => any;
    placeholder?: string;
}

interface IUserAutoCompleteState {
    value: any;
    suggestions: any[];
}

type UserAutoCompleteProps = IUserAutoCompleteInjectedProps & IUserAutoCompleteStyles;

class UserAutoComplete extends Component<UserAutoCompleteProps, IUserAutoCompleteState> {
    constructor(props: UserAutoCompleteProps) {
        super(props);
        this.state = {
            value: '',
            suggestions: [],
        };
        this.handleSuggestionsFetchRequested = this.handleSuggestionsFetchRequested.bind(this);
        this.handleSuggestionsClearRequested = this.handleSuggestionsClearRequested.bind(this);
        this.handleSuggestionSelected = this.handleSuggestionSelected.bind(this);
        this.renderSuggestion = this.renderSuggestion.bind(this);
        this.handleChange = this.handleChange.bind(this);
    }

    public componentWillMount() {
        if (this.props.value) {
            this.setState(this.setValue(this.props.value));
        }
    }

    public componentWillUpdate(nextProps: any, nextState: any) {
        if (nextProps.value !== this.props.value) {
            if (nextProps.value) {
                this.setState(this.setValue(nextProps.value));
            } else {
                this.setState(this.setValue(''));
            }
        }
    }

    public setValue(newValue: any) {
        return (state: IUserAutoCompleteState) => ({value: newValue});
    }

    public setSuggestions(newSuggestions: any) {
        return (state: IUserAutoCompleteState) => ({suggestions: newSuggestions});
    }

    public handleSuggestionsFetchRequested(obj: any) {
        const {value} = obj;
        this.setState(this.setSuggestions(this.props.getSuggestions(value, this.props.objects)));
    }

    public handleSuggestionsClearRequested() {
        this.setState(this.setSuggestions([]));
    }

    public handleChange(event: any, obj: any) {
        let {newValue} = obj;
        const {objects} = this.props;
        let override: any;
        const exactMatch = objects.filter((user: Iuser) => {
            const nameL = `${user.firstName.trim().toLowerCase()} ${user.lastName.trim().toLowerCase()}`;
            const name = `${user.firstName} ${user.lastName}`;
            if (name === newValue || nameL === newValue) {
                override = name;
                return true;
            }
        });
        if (exactMatch.length === 1 && override) {
            this.props.save(override, this.props.name, override);
            newValue = override;
        } else {
            this.props.save(newValue, this.props.name, newValue);
        }
        this.setState(this.setValue(newValue));
    }

    public handleSuggestionSelected(event: any, obj: any) {
        const {suggestion, suggestionValue, suggestionIndex, sectionIndex, method} = obj;
        this.props.save(suggestionValue, this.props.name, suggestionValue);
    }

    public renderSuggestion(suggestion: any, obj: any) {
        const {query, isHighlighted} = obj;
        const matches1 = match(getPath(suggestion, this.props.path1), query);
        const parts1 = parse(getPath(suggestion, this.props.path1), matches1);
        const matches2 = match(getPath(suggestion, this.props.path2), query);
        const parts2 = parse(getPath(suggestion, this.props.path2), matches2);
        return (
            <MenuItem selected={isHighlighted} component="div">
                <div>
                    {parts1.map((part: any, index: any) => {
                        return part.highlight ? (
                                <span key={index} style={{ fontWeight: 500 }}>
                                    {part.text}
                                </span>
                            )
                            : (
                                <strong key={index} style={{ fontWeight: 900 }}>
                                    {part.text}
                                </strong>
                            );
                    })}
                </div>
                <div style={{marginLeft: 5}}> </div>
                <div>
                    {parts2.map((part: any, index: any) => {
                        return part.highlight ? (
                                <span key={index} style={{ fontWeight: 500 }}>
                                    {part.text}
                                </span>
                            )
                            : (
                                <strong key={index} style={{ fontWeight: 900 }}>
                                    {part.text}
                                </strong>
                            );
                    })}
                </div>
            </MenuItem>
        );
    }

    public render() {
        const {classes, parentClasses} = this.props;
        return (
            <Autosuggest
                theme={{
                    container: classes.container,
                    suggestionsContainerOpen: classes.suggestionsContainerOpen,
                    suggestionsList: classes.suggestionsList,
                    suggestion: classes.suggestion,
                }}
                renderInputComponent={renderInput}
                suggestions={this.state.suggestions}
                onSuggestionsFetchRequested={this.handleSuggestionsFetchRequested}
                onSuggestionsClearRequested={this.handleSuggestionsClearRequested}
                onSuggestionSelected={this.handleSuggestionSelected}
                renderSuggestionsContainer={renderSuggestionsContainer}
                getSuggestionValue={this.props.getSuggestionValue}
                renderSuggestion={this.renderSuggestion}
                highlightFirstSuggestion={true}
                inputProps={{
                    classes,
                    parentClasses,
                    disabled: this.props.disabled,
                    placeholder: this.props.placeholder,
                    value: this.state.value,
                    onChange: this.handleChange,
                }}
            />
        );
    }
}

export const UserAutoComplete_component = withStyles(styles)<IUserAutoCompleteInjectedProps>(UserAutoComplete);

```

The view if you want to see the integration. The User model is a simple user with id, username, first and last name.

And this is the AutoSuggestHighlight I made

```typescript
const specialCharsRegex = /[.*+?^${}()|[\]\\]/g;
const wordCharacterRegex = /[a-z0-9_]/i;

const whitespacesRegex = /\s+/;

function escapeRegexCharacters(str: any) {
    return str.replace(specialCharsRegex, '\\$&');
}

export const match = (text: any, query: any)  => {

    return (
        query
            .trim()
            .split(whitespacesRegex)
            // If query is blank, we'll get empty string here, so let's filter it out.
            .filter((word: any) => {
                return word.length > 0;
            })
            .reduce((result: any, word: any) => {
                const wordLen = word.length;
                const regex = new RegExp(escapeRegexCharacters(word), 'i');
                let index = text.match(regex);
                if (index) {
                    index = index.index;
                } else {
                    index = -1;
                }
                if (index > -1) {
                    result.push([index, index + wordLen]);

                    // Replace what we just found with spaces so we don't find it again.
                    text =
                        text.slice(0, index) +
                        new Array(wordLen + 1).join(' ') +
                        text.slice(index + wordLen);
                }

                return result;
            }, [])
            .sort((match1: any, match2: any) => {
                return match1[0] - match2[0];
            })
    );
};

```

I hope this helps. Since this is a whole component example, also I believe the parts can be made dynamic I just kept it separate. Let me know if this works for you. If it does I will make a pull request.

**Comment by antoniopuero** [comment] 2018-05-27 14:04
what about:

```javascript
function customMatch(text, query) {
  const results = [];
  const trimmedQuery = query.trim().toLowerCase();
  const textLower = text.toLowerCase();
  const queryLength = trimmedQuery.length;
  let indexOf = textLower.indexOf(query);
  while (indexOf > -1) {
    results.push([indexOf, indexOf + queryLength]);
    indexOf = textLower.indexOf(query, indexOf + queryLength);
  }
  return results;
}
```

**Comment by vaske** [comment] 2019-01-11 12:15
> how about:
> 
> ```js
> function customMatch(text, query) {
>   const results = [];
>   const trimmedQuery = query.trim().toLowerCase();
>   const textLower = text.toLowerCase();
>   const queryLength = trimmedQuery.length;
>   let indexOf = textLower.indexOf(trimmedQuery);
>   while (indexOf > -1) {
>     results.push([indexOf, indexOf + queryLength]);
>     indexOf = textLower.indexOf(query, indexOf + queryLength);
>   }
>   return results;
> }
> ```

out of memory crash..

**Comment by vaske** [comment] 2019-01-11 14:10
> @iki I guess I will just post all the code for it.
> 
> ```ts
> import React, {Component} from 'react';
> import {withStyles} from 'material-ui/styles';
> import {MenuItem} from 'material-ui/Menu';
> import Autosuggest from 'react-autosuggest';
> import Paper from 'material-ui/Paper';
> import {getPath} from 'tedb';
> import {Iuser} from '../../../api/models';
> import {FormControl, Input} from 'material-ui';
> import {match} from '../../../helpers/autoSuggestHightlight';
> const parse = require('autosuggest-highlight/parse');
> 
> const relative: any = 'relative';
> const absolute: any = 'absolute';
> 
> const styles = (theme: any) => ({
>     container: {
>         flexGrow: 1,
>         backgroundColor: 'white',
>         position: relative,
>     },
>     suggestionsContainerOpen: {
>         zIndex: 5,
>         position: absolute,
>         left: 0,
>         right: 0,
>     },
>     suggestion: {
>         display: 'block',
>         position: relative,
>     },
>     suggestionsList: {
>         position: relative,
>         margin: 0,
>         padding: 0,
>         listStyleType: 'none',
>     },
>     textField: {
>         width: '100%',
>         margin: 0,
>     },
> });
> 
> const renderSuggestionsContainer = (options: any) => {
>     const {containerProps, children} = options;
>     return (
>         <Paper {...containerProps} square>
>             {children}
>         </Paper>
>     );
> };
> 
> const renderInput = (inputProps: any) => {
>     const {classes, home, value, ref, parentClasses, ...other} = inputProps;
> 
>     return (
>         <FormControl
>             className={classes.textField}
>             margin="dense"
>             fullWidth={true}
>         >
>             <Input className={parentClasses.inputField}
>                    value={value}
>                    autoFocus={home}
>                    inputRef={ref}
>                    {...other}
>             />
>         </FormControl>
>     );
> };
> 
> interface IUserAutoCompleteStyles {
>     classes: any;
> }
> 
> interface IUserAutoCompleteInjectedProps {
>     parentClasses: any;
>     objects: any[];
>     path1: string;
>     path2: string;
>     disabled: boolean;
>     value: any;
>     name: string;
>     save: (obj: any, name: string, path: string) => any;
>     getSuggestionValue: (suggestion: any) => any;
>     getSuggestions: (value: any, suggestions: any[]) => any[];
>     onSuggestionSelected: (event: any, obj: any) => any;
>     placeholder?: string;
> }
> 
> interface IUserAutoCompleteState {
>     value: any;
>     suggestions: any[];
> }
> 
> type UserAutoCompleteProps = IUserAutoCompleteInjectedProps & IUserAutoCompleteStyles;
> 
> class UserAutoComplete extends Component<UserAutoCompleteProps, IUserAutoCompleteState> {
>     constructor(props: UserAutoCompleteProps) {
>         super(props);
>         this.state = {
>             value: '',
>             suggestions: [],
>         };
>         this.handleSuggestionsFetchRequested = this.handleSuggestionsFetchRequested.bind(this);
>         this.handleSuggestionsClearRequested = this.handleSuggestionsClearRequested.bind(this);
>         this.handleSuggestionSelected = this.handleSuggestionSelected.bind(this);
>         this.renderSuggestion = this.renderSuggestion.bind(this);
>         this.handleChange = this.handleChange.bind(this);
>     }
> 
>     public componentWillMount() {
>         if (this.props.value) {
>             this.setState(this.setValue(this.props.value));
>         }
>     }
> 
>     public componentWillUpdate(nextProps: any, nextState: any) {
>         if (nextProps.value !== this.props.value) {
>             if (nextProps.value) {
>                 this.setState(this.setValue(nextProps.value));
>             } else {
>                 this.setState(this.setValue(''));
>             }
>         }
>     }
> 
>     public setValue(newValue: any) {
>         return (state: IUserAutoCompleteState) => ({value: newValue});
>     }
> 
>     public setSuggestions(newSuggestions: any) {
>         return (state: IUserAutoCompleteState) => ({suggestions: newSuggestions});
>     }
> 
>     public handleSuggestionsFetchRequested(obj: any) {
>         const {value} = obj;
>         this.setState(this.setSuggestions(this.props.getSuggestions(value, this.props.objects)));
>     }
> 
>     public handleSuggestionsClearRequested() {
>         this.setState(this.setSuggestions([]));
>     }
> 
>     public handleChange(event: any, obj: any) {
>         let {newValue} = obj;
>         const {objects} = this.props;
>         let override: any;
>         const exactMatch = objects.filter((user: Iuser) => {
>             const nameL = `${user.firstName.trim().toLowerCase()} ${user.lastName.trim().toLowerCase()}`;
>             const name = `${user.firstName} ${user.lastName}`;
>             if (name === newValue || nameL === newValue) {
>                 override = name;
>                 return true;
>             }
>         });
>         if (exactMatch.length === 1 && override) {
>             this.props.save(override, this.props.name, override);
>             newValue = override;
>         } else {
>             this.props.save(newValue, this.props.name, newValue);
>         }
>         this.setState(this.setValue(newValue));
>     }
> 
>     public handleSuggestionSelected(event: any, obj: any) {
>         const {suggestion, suggestionValue, suggestionIndex, sectionIndex, method} = obj;
>         this.props.save(suggestionValue, this.props.name, suggestionValue);
>     }
> 
>     public renderSuggestion(suggestion: any, obj: any) {
>         const {query, isHighlighted} = obj;
>         const matches1 = match(getPath(suggestion, this.props.path1), query);
>         const parts1 = parse(getPath(suggestion, this.props.path1), matches1);
>         const matches2 = match(getPath(suggestion, this.props.path2), query);
>         const parts2 = parse(getPath(suggestion, this.props.path2), matches2);
>         return (
>             <MenuItem selected={isHighlighted} component="div">
>                 <div>
>                     {parts1.map((part: any, index: any) => {
>                         return part.highlight ? (
>                                 <span key={index} style={{ fontWeight: 500 }}>
>                                     {part.text}
>                                 </span>
>                             )
>                             : (
>                                 <strong key={index} style={{ fontWeight: 900 }}>
>                                     {part.text}
>                                 </strong>
>                             );
>                     })}
>                 </div>
>                 <div style={{marginLeft: 5}}> </div>
>                 <div>
>                     {parts2.map((part: any, index: any) => {
>                         return part.highlight ? (
>                                 <span key={index} style={{ fontWeight: 500 }}>
>                                     {part.text}
>                                 </span>
>                             )
>                             : (
>                                 <strong key={index} style={{ fontWeight: 900 }}>
>                                     {part.text}
>                                 </strong>
>                             );
>                     })}
>                 </div>
>             </MenuItem>
>         );
>     }
> 
>     public render() {
>         const {classes, parentClasses} = this.props;
>         return (
>             <Autosuggest
>                 theme={{
>                     container: classes.container,
>                     suggestionsContainerOpen: classes.suggestionsContainerOpen,
>                     suggestionsList: classes.suggestionsList,
>                     suggestion: classes.suggestion,
>                 }}
>                 renderInputComponent={renderInput}
>                 suggestions={this.state.suggestions}
>                 onSuggestionsFetchRequested={this.handleSuggestionsFetchRequested}
>                 onSuggestionsClearRequested={this.handleSuggestionsClearRequested}
>                 onSuggestionSelected={this.handleSuggestionSelected}
>                 renderSuggestionsContainer={renderSuggestionsContainer}
>                 getSuggestionValue={this.props.getSuggestionValue}
>                 renderSuggestion={this.renderSuggestion}
>                 highlightFirstSuggestion={true}
>                 inputProps={{
>                     classes,
>                     parentClasses,
>                     disabled: this.props.disabled,
>                     placeholder: this.props.placeholder,
>                     value: this.state.value,
>                     onChange: this.handleChange,
>                 }}
>             />
>         );
>     }
> }
> 
> export const UserAutoComplete_component = withStyles(styles)<IUserAutoCompleteInjectedProps>(UserAutoComplete);
> ```
> 
> The view if you want to see the integration. The User model is a simple user with id, username, first and last name.
> 
> And this is the AutoSuggestHighlight I made
> 
> ```ts
> const specialCharsRegex = /[.*+?^${}()|[\]\\]/g;
> const wordCharacterRegex = /[a-z0-9_]/i;
> 
> const whitespacesRegex = /\s+/;
> 
> function escapeRegexCharacters(str: any) {
>     return str.replace(specialCharsRegex, '\\$&');
> }
> 
> export const match = (text: any, query: any)  => {
> 
>     return (
>         query
>             .trim()
>             .split(whitespacesRegex)
>             // If query is blank, we'll get empty string here, so let's filter it out.
>             .filter((word: any) => {
>                 return word.length > 0;
>             })
>             .reduce((result: any, word: any) => {
>                 const wordLen = word.length;
>                 const regex = new RegExp(escapeRegexCharacters(word), 'i');
>                 let index = text.match(regex);
>                 if (index) {
>                     index = index.index;
>                 } else {
>                     index = -1;
>                 }
>                 if (index > -1) {
>                     result.push([index, index + wordLen]);
> 
>                     // Replace what we just found with spaces so we don't find it again.
>                     text =
>                         text.slice(0, index) +
>                         new Array(wordLen + 1).join(' ') +
>                         text.slice(index + wordLen);
>                 }
> 
>                 return result;
>             }, [])
>             .sort((match1: any, match2: any) => {
>                 return match1[0] - match2[0];
>             })
>     );
> };
> ```
> 
> I hope this helps. Since this is a whole component example, also I believe the parts can be made dynamic I just kept it separate. Let me know if this works for you. If it does I will make a pull request.



You can make it bit simpler 

```
export const match = (text: any, query: any)  => {

    return (
        query
            .trim()
            .split(whitespacesRegex)
            .reduce((result: any, word: any) => {
                if (!word.length) return result;
                const wordLen = word.length;
                const regex = new RegExp(escapeRegexCharacters(word), 'i');
                const { index = -1 } = text.match(regex);
                if (index > -1) {
                    result.push([index, index + wordLen]);

                    // Replace what we just found with spaces so we don't find it again.
                    text =
                        text.slice(0, index) +
                        new Array(wordLen + 1).join(' ') +
                        text.slice(index + wordLen);
                }

                return result;
            }, [])
            .sort((match1: any, match2: any) => {
                return match1[0] - match2[0];
            })
    );
};
```

**Comment by bbigras** [comment] 2019-04-29 16:55
> out of memory crash..

Was it because you tried with an empty query and got an infinite loop (since indexOf is always 0)? A simple:
```js
  if (!query) {
    return [];
  }
```

would fix that.

Btw the example using `indexOf` is way faster than when using regexes.

**Comment by lukesterg** [comment] 2019-10-03 06:02
I have not gone through this library very well (maybe 15 minutes), but I thought I would paste some code as it helped me with this issue. This code does both match and parse at once. It performs a case insensitive search for query on the parameter suggestion.

If you wanted to split these into two methods it would be simple to calculate word length from the split result.

```js
function *customHighlight(suggestion: string, query: string) {
  const escapeQuery = query.replace(/[.*+?^${}()|[\]\\]/g, matched => `\\${matched}`);
  const insensitiveQueryRegex = new RegExp(escapeQuery, 'i');
  const hits = suggestion.match(insensitiveQueryRegex);

  if (query === '' || !hits) {
    yield ({
      text: suggestion,
      highlight: false
    });
    return;
  };

  const misses = suggestion.split(insensitiveQueryRegex).map(text => ({
    text,
    highlight: false
  }));

  const formattedHits = hits.map(text => ({
    text,
    highlight: true
  }));

  while (misses.length > 0) {
    const miss = misses.shift();
    if (miss !== undefined && miss.text !== '') {
      yield miss;
    }

    const hit = formattedHits.shift()!;
    if (hit !== undefined) {
      yield hit;
    }
  }
}
```

**Comment by hallboav** [comment] 2020-04-22 23:13
> how about:
> 
> ```js
> function customMatch(text, query) {
>   const results = [];
>   const trimmedQuery = query.trim().toLowerCase();
>   const textLower = text.toLowerCase();
>   const queryLength = trimmedQuery.length;
>   let indexOf = textLower.indexOf(trimmedQuery);
>   while (indexOf > -1) {
>     results.push([indexOf, indexOf + queryLength]);
>     indexOf = textLower.indexOf(query, indexOf + queryLength);
>   }
>   return results;
> }
> ```

Based on @antoniopuero  answer:
```javascript
const diacritic = require("diacritic");

function assertTrue(actual) {
    if (!actual) {
        console.error("FAILED");

        process.exit(1);
    }
}

function assertMatch(text, query, expected) {
    const actual = match(text, query);

    console.log('const actual = match("' + text + '", "' + query + '")');
    console.log("actual is ", actual);

    assertTrue(JSON.stringify(expected) === JSON.stringify(actual));
}

function match(text, query) {
    if (!("string" === typeof query && "string" === typeof text)) {
        return [];
    }

    let t = text.toLowerCase();
    let q = query.trim().toLowerCase();
    const ql = q.length;

    if (!(0 < ql && 0 < t.length)) {
        return [];
    }

    t = diacritic.clean(t);
    q = diacritic.clean(q);

    let r = [];

    let i = t.indexOf(q);
    while (i !== -1) {
        r.push([i, i + ql]);
        i = t.indexOf(q, i + ql);
    }

    return r;
}

assertMatch("xyz xýw", "y", [[1, 2], [5, 6]]);
console.info("PASSED");
```

**Comment by majdajroudi** [comment] 2021-07-02 08:21
I see the issue is still open but the PR related this issue was merged. Is the feature not working? 

also does the feature work automatically or is some kind of parameter needed?

**Closed** 2021-07-06 00:11 UTC

**Comment by Tmfwang** [comment] 2021-07-06 12:37
I'm using the autosuggest highlight with Material UI´s autocomplete component, and I just switched out autosuggest-highlight´s match-method with my own logic like this:

`const optionsNavn = [
    {label: 'Ole Nordmann'},
    {label: "Kari Nordmann"}
];

..........


return (

<Autocomplete
                id="admin-frontpage-search-field"
                freeSolo
                onInputChange={(event, selectedValue) => {
                    handleChange(selectedValue)
                }}
                options={allSearchOptions}
                getOptionLabel={(option) => option.label}

                groupBy={(option) => option.type}
                
                renderInput={(params) => (
                    <div ref={params.InputProps.ref}>
                        <TextInput label="Navn, selskap, forening, domstol..." style={{ width: 288 }} type="text" {...params.inputProps}       />
                    </div>
                )}

                renderOption={(option, { inputValue }) => {
                    const matches = []

                    const inputValueIndex = option.label.toLowerCase().indexOf(inputValue.toLowerCase())
                    
                    if(inputValueIndex !== -1){
                        matches.push([inputValueIndex, inputValueIndex + inputValue.length])
                    }
                    
                    const parts = parse(option.label, matches);

                    return (
                        <div>
                            {parts.map((part: {text: string, highlight: number}, index: number) => (
                                <span key={index} style={{ fontWeight: part.highlight ? 700 : 400 }}>
                                    {part.text}
                                </span>
                            ))}
                        </div>
                    );
                }}
            />

)

`
